package ar.edu.ub.p3.conexion;

public enum TipoMensaje {
	ALTA_AEROPUERTO,
	ALTA_AEROPUERTO_ACK,
	
	OBTENER_LISTADO_AEROPUERTOS_DISPONIBLES,
	LISTADO_AEROPUERTOS_DISPONIBLES,
	
	BAJA_AEROPUERTO,
	BAJA_AEROPUERTO_ACK,
	
	TRAFICO_AEREO_ERROR,
	
	VUELO_PROGRAMADO,
	VUELO_PROXIMO_A_ATERRIZAR,
	VUELO_ATERRIZO_EN_DESTINO,
	OBTENER_INFORMACION_VUELO,
	INFORMACION_VUELO
	;
	
}
